
services:
  app:
    image: clkesat/spring-boot-strogeapi:1.1.0
    container_name: storage-app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    networks:
      - my-network
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  minio:
    image: minio/minio:latest
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:


